[#31] SessionLoginServiceImple 클래스에서 getLoginId() null check 기능 추가
f-lab-edu/video-hosting-service pull request #33
Opened 2020-11-10 05:23 UTC by SeongjinOliver

- SessionLoginServiceImple 클래스에서 getLoginId() null check 기능 추가

- 로그인한 아이디를 가져올 때 null 유무를 확인

2020-11-10 16:43 UTC, f-lab-dev commented on src/main/java/me/dev/oliver/mytube/service/SessionLoginServiceImpl.java
> +      log.error("HttpServletRequest 생성 도중에 null이 확인되었습니다");
`HttpServletRequest `를 **생성**하는게 맞을까요?

2020-11-14 14:58 UTC, f-lab-dev requested changes

2020-11-14 14:58 UTC, f-lab-dev commented on src/main/java/me/dev/oliver/mytube/service/SessionLoginServiceImpl.java
> +          "getHttpSession() 메서드에서 RequestContextHolder를 이용하여 HttpServletRequest 접근 도중에 null이 확인되었습니다");
보통 세션은 스레드로컬에 저장이 되는데 어떤 스레드이길래 null이 들어있는지 그런 정보들도 찍어주면 좋을 것 같네요. 이 정보만으로는 에러가 발생해도 디버깅이 힘들 것 같습니다~

2020-11-16 03:24 UTC, f-lab-dev commented on src/main/java/me/dev/oliver/mytube/service/SessionLoginServiceImpl.java
> +              + "스레드 로컬인 NamedThreadLocal와 NamedInheritableThreadLocal 변수에 null이 확인되었습니다");
이 로직이 현재 어떤 스레드에 의해 돌고있는지도 같이 찍어줘야하지 않을까요?
그리고 정확히 말하자면 `NamedThreadLocal `과 `NamedInheritableThreadLocal` 자체가 null은 아닙니다~

2020-11-19 01:18 UTC, f-lab-dev commented on src/main/java/me/dev/oliver/mytube/service/SessionLoginServiceImpl.java
> +          Thread.currentThread());
이렇게 찍으면 로그에 어떻게 찍히는지 확인해보셨나요?

2020-11-20 10:38 UTC, SeongjinOliver commented on src/main/java/me/dev/oliver/mytube/service/SessionLoginServiceImpl.java
> +          Thread.currentThread());
넵 현재는 Thread[http-nio-18080-exec-1,5,main] 이렇게 로그에 찍힙니다. 쓰레드 이름만 찍는것과 고민하다가 이렇게 찍었는데 쓰레디 이름만 찍는 것이 더 좋을까요?

2020-11-28 13:18 UTC, f-lab-dev approved these changes

2020-12-03 15:42 UTC, merged